USE ROLE DEV_ENT_DW_ENGINEER_FR;
USE WAREHOUSE LOAD_WH;

USE DATABASE DEMO_DB;

-- CREATE SCHEMA 
CREATE SCHEMA IF NOT EXISTS  DEMO_DB.ALF_LAND;
CREATE SCHEMA IF NOT EXISTS  DEMO_DB.ALF_RAW;
CREATE SCHEMA IF NOT EXISTS  DEMO_DB.ALF_CLEAN;
CREATE SCHEMA IF NOT EXISTS  DEMO_DB.ALF_CONSUMPTION;

SHOW SCHEMAS IN DATABASE DEMO_DB;

-- CREATE FILE FORMAT IN LAND 
CREATE FILE FORMAT IF NOT EXISTS DEMO_DB.ALF_LAND.FF_LAND_JSON
    TYPE = JSON 
    NULL_IF = ('\\n', 'null', '')
    STRIP_OUTER_ARRAY = TRUE
    COMMENT = 'JSON FILE FORMAT WITH OUTER STRIP ARRAY FLAG TRUE';

-- CREATE INTERNAL STAGE 
CREATE OR REPLACE STAGE DEMO_DB.ALF_LAND.STG_LAND;

