
/*

CUSTOMER ADDRESS ENTITY :
    - STAGE LAYER ->  DEMO_DB.ALF_STAGE_SCH.location 
    - CLEAN LAYER ->  DEMO_DB.ALF_CLEAN_SCH.RESTAURANT_LOCATION
    - CONSUMPTION LAYER  ->  DEMO_DB.ALF_CONSUMPTION_SCH.RESTAURANT_LOCATION_DIM
 */

-- change context
use role DEV_ENT_DW_ENGINEER_FR;
use database DEMO_DB;
use schema ALF_STAGE_SCH;
use warehouse DEMO_WH;

ALTER SESSION SET TIMEZONE  = 'America/Montreal';


