USE DATABASE DEMO_DB;

USE SCHEMA ALF_CLEAN;

USE WAREHOUSE LOAD_WH;

/*
    ALF_RAW: MATCH_RAW_TBL
    ALF_CLEAN: match_detail_clean
 */

-- EXTRACT PLAYERS 

-- VERSION 1 
SELECT INFO:match_type_number::INT AS match_type_number,
INFO:players,
INFO:teams
FROM 
DEMO_DB.ALF_RAW.MATCH_RAW_TBL
;


-- VERSION 2
SELECT INFO:match_type_number::INT AS match_type_number,
INFO:players,
INFO:teams
FROM 
DEMO_DB.ALF_RAW.MATCH_RAW_TBL
WHERE match_type_number = '4670'
;


-- VERSION 3
SELECT RAW.INFO:match_type_number::INT AS match_type_number, 
-- P.* 
P.KEY AS COUNTRY
FROM DEMO_DB.ALF_RAW.MATCH_RAW_TBL AS RAW,
LATERAL FLATTEN (INPUT => RAW.INFO:players) AS P
WHERE match_type_number = '4670';

-- VERSION 4 

SELECT RAW.INFO:match_type_number::INT AS match_type_number, 
-- P.* 
P.KEY AS COUNTRY, 
T.VALUE::VARCHAR AS PLAYER_NAME
FROM DEMO_DB.ALF_RAW.MATCH_RAW_TBL AS RAW,
LATERAL FLATTEN (INPUT => RAW.INFO:players) AS P,
LATERAL FLATTEN (INPUT => P.VALUE) AS T
--WHERE match_type_number = '4670'
;

-- CREATE TABLE PLAYER_CLEAN_TBL 
CREATE OR REPLACE TRANSIENT TABLE DEMO_DB.ALF_CLEAN.PLAYER_CLEAN_TBL
AS
SELECT RAW.INFO:match_type_number::INT AS match_type_number, 
P.KEY AS COUNTRY, 
T.VALUE::VARCHAR AS PLAYER_NAME,
RAW.STG_FILE_NAME ,
RAW.STG_FILE_ROW_NUMBER,
RAW.STG_FILE_HASHKEY,
RAW.STG_FILE_MODIFIED_TS
FROM DEMO_DB.ALF_RAW.MATCH_RAW_TBL AS RAW,
LATERAL FLATTEN (INPUT => RAW.INFO:players) AS P,
LATERAL FLATTEN (INPUT => P.VALUE) AS T;


-- MATCH_DETAIL_CLEAN 
ALTER TABLE DEMO_DB.ALF_CLEAN.MATCH_DETAIL_CLEAN  
ADD CONSTRAINT PK_MATCH_TYPE_NUMBER PRIMARY KEY (MATCH_TYPE_NUMBER);
SELECT * FROM DEMO_DB.ALF_CLEAN.MATCH_DETAIL_CLEAN;
DESCRIBE TABLE DEMO_DB.ALF_CLEAN.PLAYER_CLEAN_TBL;



-- PLAYER_CLEAN_TBL
SELECT * FROM DEMO_DB.ALF_CLEAN.PLAYER_CLEAN_TBL;
DESCRIBE TABLE DEMO_DB.ALF_CLEAN.PLAYER_CLEAN_TBL;
ALTER TABLE DEMO_DB.ALF_CLEAN.PLAYER_CLEAN_TBL ALTER(
   MATCH_TYPE_NUMBER SET NOT NULL,
   COUNTRY SET NOT NULL,
   PLAYER_NAME SET NOT NULL
);

ALTER TABLE DEMO_DB.ALF_CLEAN.PLAYER_CLEAN_TBL  
ADD CONSTRAINT FK_MATCH_ID FOREIGN KEY (MATCH_TYPE_NUMBER)
REFERENCES DEMO_DB.ALF_CLEAN.MATCH_DETAIL_CLEAN (MATCH_TYPE_NUMBER);