USE DATABASE DEMO_DB;

USE SCHEMA ALF_CLEAN;

USE WAREHOUSE LOAD_WH;

-- India vs England
SELECT * FROM 
DEMO_DB.ALF_CLEAN.MATCH_DETAIL_CLEAN
WHERE MATCH_TYPE_NUMBER = 4686
;

/*
REF: https://www.google.com/search?q=icc+world+cup+2023+schedule&sca_esv=697ef796fdf142b1&sca_upv=1&ei=5jdFZumCApikptQPgYCLwAs&oq=CRICKET+WORLD+CUP+HISTO&gs_lp=Egxnd3Mtd2l6LXNlcnAiF0NSSUNLRVQgV09STEQgQ1VQIEhJU1RPKgIIADIKEAAYsAMY1gQYRzIKEAAYsAMY1gQYRzIKEAAYsAMY1gQYRzIKEAAYsAMY1gQYRzIKEAAYsAMY1gQYRzIKEAAYsAMY1gQYRzIKEAAYsAMY1gQYRzIKEAAYsAMY1gQYRzINEAAYgAQYsAMYQxiKBTINEAAYgAQYsAMYQxiKBTINEAAYgAQYsAMYQxiKBTINEAAYgAQYsAMYQxiKBTIOEAAYsAMY5AIY1gTYAQEyDhAAGLADGOQCGNYE2AEBMg4QABiwAxjkAhjWBNgBATITEC4YgAQYsAMYQxjIAxiKBdgBAjITEC4YgAQYsAMYQxjIAxiKBdgBAjITEC4YgAQYsAMYQxjIAxiKBdgBAki0ClAAWABwAXgAkAEAmAFeoAFeqgEBMbgBAcgBAJgCAaACBZgDAIgGAZAGEroGBggBEAEYCboGBggCEAEYCJIHATGgB8IT&sclient=gws-wiz-serp#sie=m;/g/11v13fbw_n;5;/m/021vk;dt;fp;1;;; */

-- BY BATSMAN
SELECT *
FROM 
DEMO_DB.ALF_CLEAN.DELIVERY_CLEAN_TBL
WHERE MATCH_TYPE_NUMBER = 4686;

SELECT TEAM_NAME, BATTER, SUM(RUNS)
FROM 
DEMO_DB.ALF_CLEAN.DELIVERY_CLEAN_TBL
WHERE MATCH_TYPE_NUMBER = 4686
GROUP BY TEAM_NAME, BATTER
ORDER BY 1,2,3 DESC
;

--  BY TEAM
select TEAM_NAME, SUM(RUNS)+SUM(EXTRA_RUNS) from 
DEMO_DB.ALF_CLEAN.DELIVERY_CLEAN_TBL
WHERE MATCH_TYPE_NUMBER = 4686
GROUP BY TEAM_NAME;